# Generated by Django 4.2.9 on 2024-04-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0006_chatbot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="botname",
            field=models.CharField(
                choices=[("Health", "Health Assistant"), ("Law", "Law Assistant")],
                max_length=50,
            ),
        ),
    ]
